spring:
  application:
    name: eureka
  profiles:
    active: test
server:
  port: 8761
---
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka-1
  client:
    service-url:
      defaultZone: #eureka-2 eureka-3地址
---
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka-2
  client:
    service-url:
      defaultZone: #eureka1 eureka-3
---
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka-3
  client:
    service-url:
      defaultZone:  #eureka1 eureka-2
---
spring:
  profiles: test
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: